name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "364acddff170a9f85dcb34dfa430aa1c3df8d7fa986c2b22bfbcfb1eb7bf9f2f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
