name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "909b7ab674f2f08656f5efa05be4ea5a559a0905db088c394a76db0cb19e56f1"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
