name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d60fd4bc9a2e2635bedf94ea0aaa8e62b76bdac83a2d322dc4455aa4e3e80cc4"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
