name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1551302f19c5272b456c8001942da3cd3d663e4c4c5e8f492deca880457fbf1e"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
