name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2af77e47b8b34d9cefd2ebf793d008e355af9381d81f82963133619ebea3d0b"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
