name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "951d7c6f4f0259649702fed5e79e4e3e3af7e525697d6ce746fe8941cbec955d"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
