name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb67f6ff7a5e95f0c604f1d8b14151589a8744598f33a0b57994ebcef21bad01"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
