name = "ArcKibCraft"
author = "Arceus3251"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc9b4249fc5f98af03cc577c686e581402c5c74a1a13fd0266ecca83cb10a844"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
